In [19]:
# Source: NYC OpenData Housing Database by 2020 NTA
import pandas as pd
df = pd.read_csv("Housing_Database_by_2020_NTA.csv")

In [20]:
boroughs = {
    "BK": "Brooklyn",
    "BX": "Bronx",
    "MN": "Manhattan",
    "QN": "Queens",
    "SI": "Staten Island"
}
df['borough'] = df['nta2020'].str[:2].map(boroughs)
df = df.dropna(subset=['borough'])

In [21]:
df = df.drop(columns=['nta2020', 'the_geom']).rename(columns={'ntaname2020': 'areaName'})

In [22]:
df

,areaName,comp2010ap,comp2010,comp2011,comp2012,comp2013,comp2014,comp2015,comp2016,comp2017,...,comp2024,cenunits20,filed,approved,permitted,withdrawn,inactive,Shape_Area,Shape_Length,borough
0,Greenpoint,240,314,78,111,143,328,53,349,460,...,1545,20381,113,58,2428,1202,298,3.532120e+07,28912.565312,Brooklyn
1,Williamsburg,444,2211,845,810,1337,844,1235,903,1480,...,831,32444,413,92,1934,1097,1107,2.885431e+07,28098.026774,Brooklyn
2,South Williamsburg,89,161,101,30,127,25,15,284,13,...,312,12251,66,79,427,171,247,1.520896e+07,18250.280416,Brooklyn
3,East Williamsburg,284,358,327,248,270,228,325,183,501,...,810,24898,227,83,1116,555,684,5.226621e+07,43184.773814,Brooklyn
4,Brooklyn Heights,166,-4,99,18,25,-30,53,178,62,...,-16,13810,410,27,738,331,179,9.982322e+06,14312.506134,Brooklyn
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,Freshkills Park (South),0,0,0,0,0,-1,0,0,0,...,0,29,0,0,0,0,0,4.775877e+07,33945.419465,Staten Island
258,Fort Wadsworth,0,0,0,0,0,0,0,0,0,...,0,225,0,0,0,0,0,9.867248e+06,14814.413643,Staten Island
259,Hoffman & Swinburne Islands,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,6.357020e+05,4743.128004,Staten Island
260,Miller Field,0,0,0,0,0,0,0,0,0,...,0,23,0,0,0,0,0,1.086680e+07,19197.200971,Staten Island
261,Great Kills Park,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,2.337792e+07,41763.164579,Staten Island

In [23]:
# Rename columns with "compYYYYap" to just the year
df = df.rename(columns=lambda col: col.replace("comp", "") if "comp" in col and "ap" not in col else col)

# Keep only the columns 'borough', 'areaName', and the year columns
columns_to_keep = ['borough', 'areaName'] + [col for col in df.columns if col.isdigit()]
df = df[columns_to_keep]

In [24]:
df

,borough,areaName,2010,2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Brooklyn,Greenpoint,314,78,111,143,328,53,349,460,1310,130,695,327,1437,1347,1545
1,Brooklyn,Williamsburg,2211,845,810,1337,844,1235,903,1480,798,1511,497,273,171,675,831
2,Brooklyn,South Williamsburg,161,101,30,127,25,15,284,13,249,94,104,-10,181,80,312
3,Brooklyn,East Williamsburg,358,327,248,270,228,325,183,501,206,328,348,156,173,448,810
4,Brooklyn,Brooklyn Heights,-4,99,18,25,-30,53,178,62,-125,526,152,-17,104,110,-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
257,Staten Island,Freshkills Park (South),0,0,0,0,-1,0,0,0,0,-1,0,0,0,0,0
258,Staten Island,Fort Wadsworth,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
259,Staten Island,Hoffman & Swinburne Islands,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
260,Staten Island,Miller Field,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
261,Staten Island,Great Kills Park,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [25]:
df.to_csv("Construction.csv", index=False)